# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-27 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='count',
            new_name='visitors',
        ),
    ]
