# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-27 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_auto_20180427_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
