# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-27 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_auto_20180427_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
