# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-27 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_auto_20180427_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visitors',
            field=models.IntegerField(default=1),
        ),
    ]
